apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: demo-api
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-api
  syncPolicy:
    automated: {}
